# Generated by Django 4.0.4 on 2022-05-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_arma_id_alter_arma_imagem_alter_municao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.objeto'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.objeto'),
        ),
    ]
